# Generated by Django 4.1.2 on 2022-10-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimedStamped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "timedstamped_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="twitter.timedstamped",
                    ),
                ),
                ("message", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-id"],
            },
            bases=("twitter.timedstamped",),
        ),
    ]
